sudo: required

language: perl

perl:
  - "5.24"
  - "5.22"

cache:
  directories:
    - perl_modules

env:
  - NETWORK_TEST=1

before_install:
  - sudo apt-get install --yes --force-yes gearman-job-server libgearman-dev
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"

before_script:
  - sleep 10

services:
  - sqlite3
  - elasticsearch

install:
  - cpanm --quiet --installdeps --notest --force --skip-satisfied .
  - cpanm --quiet --notest --skip-satisfied Devel::Cover

script:
  - prove -lr t/

after_success:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -report coveralls

notifications:
  email: false
  slack: librecat:2Rvl147KSMvEdivUg88Ktrbk

env: AUTOMATED_TESTING=1
