sudo: required

language: perl

perl:
  - "5.24"
  - "5.22"

cache:
  directories:
    - perl_modules

env:
  - NETWORK_TEST=1
  - GEARMAN_NETWORK_TEST=1

before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.0.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.0.deb && sudo service elasticsearch restart
  - sudo apt-get install --yes --force-yes gearman-job-server libgearman-dev
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"

before_script:
  - sleep 3

service:
  - sqlite3

install:
  - cpanm --quiet --installdeps --notest --force --skip-satisfied .
  - cpanm --quiet --notest --skip-satisfied Devel::Cover

script:
  - cover -t +select ^lib +ignore ^ -make 'prove -Ilib -r t; exit $?'

after_success:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -report coveralls

notifications:
  email: false
  slack: librecat:2Rvl147KSMvEdivUg88Ktrbk

env: AUTOMATED_TESTING=1
