_prefix:
  citation:

# engine for citation generation
# possible values are 'csl' or 'none'
engine: csl

# example 'csl' style citation generation
# see: https://github.com/LibreCat/LibreCat/wiki/Citation-Style-Language
csl:
  url: 'http://localhost:8085'
  default_style: apa
  styles:
    - apa
    - american-medical-association
    - chicago-fullnote-bibliography
    - ieee
    - modern-language-association
  zotero_styles:
    american-medical-association: american-medical-association
    apa: apa
    chicago-fullnote-bibliography: chicago-fullnote-bibliography
    ieee: ieee
    mla: modern-language-association
